name: Create new realease

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install fuse and libfuse2
      run: sudo apt install fuse libfuse2

    - name: Get appimagetool
      run: |
        set -x
        version_go_appimage=$(wget -q -O - https://api.github.com/repos/probonopd/go-appimage/releases | grep "\"name.*appimagetool-.*-x86_64.AppImage\"" | head -n 1 | cut -d '-' -f2)
        echo "version_go_appimage: $version_go_appimage"

        wget -q "https://github.com/probonopd/go-appimage/releases/download/continuous/appimagetool-$version_go_appimage-x86_64.AppImage" -O appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage
        pwd; ls -lah

    - name: Get Pyhton AppImage
      run: |
        set -x
        wget https://github.com/ryuuzaki42/Python_to_make_AppImage/releases/download/06/python3.13.3-cp313-cp313-manylinux2014_x86_64.AppImage
        fileName=$(ls python3*.AppImage)
        chmod +x "$fileName"
        ./"$fileName" --appimage-extract
        pwd; ls -lah

    - name: Install spotdl and update pip
      run: |
        set -x
        cd squashfs-root/opt/python3*/bin/
        pwd; ls -lah

        ./pip3.* install spotdl

        ./pip3.* install --upgrade pip
         pwd; ls -lah

    - name: Make AppImage
      run: |
        set -x
        cd squashfs-root/
        pwd; ls -lah

        rm .DirIcon
        mv python.png spotdl.png
        mv python3*.desktop spotdl.desktop

        version=$(grep -o "spotDL:.*" README.md | cut -d ' ' -f2)
        echo "spotDL version: $version"
        pwd; ls -lah

        cat spotdl.desktop
        sed -i "s/Name=.*/Name=spotdl/" spotdl.desktop
        cat spotdl.desktop

        cd ../
        pwd; ls -lah

        echo '#!/bin/bash
        local_folder=$PWD
        echo "local_folder $local_folder"

        HERE="$(dirname "$(readlink -f "${0}")")"
        echo "HERE: $HERE"
        HERE=$(echo "$HERE" | sed "s/usr\/bin//")
        echo "Removed usr/bin HERE: $HERE"

        #cd "$HERE"/opt/python3*/bin/
        all_Parameters=$@
        echo -e "all_Parameters: $all_Parameters\n"

        if [ "$all_Parameters" == "" ]; then
            all_Parameters="-h"
        fi

        "$HERE"/opt/python3*/bin/python3.* "$HERE"/opt/python3*/bin/spotdl "$all_Parameters"

        echo'> squashfs-root/AppRun
        chmod +x squashfs-root/AppRun
        cat squashfs-root/AppRun

        mv README.md squashfs-root/
        ls -lah squashfs-root/

        # Wrong permissions on AppDir, please set it to 0755 and try again
        chmod 0755 squashfs-root/

        ARCH=x86_64 VERSION="${version}-1_JB" ./appimagetool-x86_64.AppImage squashfs-root/
        ls -lah

        fileName=$(ls spotdl*.AppImage)
        echo "fileName: $fileName"
        md5sum "$fileName" > "${fileName}.md5"
        ls -lah

    # Build - Error: Resource not accessible by integration
    # Change Settings -> Actions -> General -> Workflow Permissions to allow read and write:
    # https://github.com/actions/first-interaction/issues/10#issuecomment-1506118886

    # https://github.com/marketplace/actions/upload-to-github-release
    - uses: xresloader/upload-to-github-release@main
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          file: "spotdl*.AppImage; spotdl*.zsync; spotdl*.md5"
          #delete_file: "random-name-*.txt;random-*.txt"
          release_id: ${{ steps.create_release.outputs.id }}
          #overwrite: true
          verbose: true
          #tags: true
          draft: false
          default_release_name: "spotdl V in AppImage"
